language: php

php:
  - '5.6'

services:
  - postgresql

env:
  - DB=pgsql

before_install:
  - composer self-update
  - echo no | pecl install memcache
  - psql -c "create database symfony;" -U postgres
  - psql -c "create user book with password 'book';" -U postgres
  - psql -c "grant all privileges on database symfony to book;" -U postgres

install:
  - composer install
  - php bin/console doctrine:schema:create
  - php bin/console fos:user:create admin admin@admin.admin asdasd
  - php bin/console fos:user:promote admin ROLE_ADMIN

script: vendor/bin/simple-phpunit
